const std = @import("std");
const emit_lock = @import("emit_lock.zig");
const emit_manifest = @import("emit_manifest.zig");
const manifest = @import("manifest.zig");
const model = @import("model.zig");

pub const EmitError = error{
    InvalidTypeArity,
    OutputNameCollision,
    OutputPathIsFile,
    StagingPathExists,
    UnsupportedShape,
    ManifestContractViolation,
};

pub fn module_name(
    allocator: std.mem.Allocator,
    package: model.PackageDecl,
    world: model.WorldDecl,
    interface: model.InterfaceDecl,
) ![]u8 {
    var out = std.ArrayList(u8).empty;
    try append_flat_name(&out, allocator, package.namespace);
    try out.append(allocator, '_');
    try append_flat_name(&out, allocator, package.name);
    try out.appendSlice(allocator, "__");
    try append_flat_name(&out, allocator, interface.name);
    try out.appendSlice(allocator, "__");
    try append_flat_name(&out, allocator, world.name);
    try out.appendSlice(allocator, ".do");
    return out.toOwnedSlice(allocator);
}

pub fn render_module(
    allocator: std.mem.Allocator,
    binding: model.BindingModel,
    interface: model.InterfaceDecl,
) (EmitError || std.mem.Allocator.Error)![]u8 {
    var out = std.ArrayList(u8).empty;
    errdefer out.deinit(allocator);
    try out.appendSlice(allocator, "// generated by do wit; source WIT is authoritative\n\n");
    const interface_package = interface.package orelse binding.package;

    // Do requires host imports to form the module prefix before declarations.
    for (interface.functions) |function| {
        try append_lower(&out, allocator, function.name);
        try out.appendSlice(allocator, " = @");
        try out.appendSlice(allocator, if (function.is_async) "host_async_func(\"" else "host_func(\"");
        try append_interface_locator(&out, allocator, interface_package, interface.name);
        try out.appendSlice(allocator, "\", \"");
        try append_raw_name(&out, allocator, function.name);
        try out.appendSlice(allocator, "\", (");
        for (function.params, 0..) |param, index| {
            if (index != 0) try out.appendSlice(allocator, ", ");
            try append_type(&out, allocator, param.type_ref, interface.name);
        }
        try out.appendSlice(allocator, ") -> ");
        if (function.result) |result| {
            try append_type(&out, allocator, result, interface.name);
        } else {
            try out.appendSlice(allocator, "nil");
        }
        try out.appendSlice(allocator, ")\n");
    }
    if (interface.functions.len != 0) try out.append(allocator, '\n');

    for (interface.resources) |resource| {
        try append_pascal(&out, allocator, resource.name);
        try out.appendSlice(allocator, " = @wasi_resource(\"");
        try append_wit_resource_target(&out, allocator, interface_package, interface.name, resource.name);
        try out.appendSlice(allocator, "\", { .id i64 })\n");
    }

    for (interface.records) |record| {
        try append_pascal(&out, allocator, record.name);
        try out.appendSlice(allocator, " = @wasi_record(\"");
        try append_wit_resource_target(&out, allocator, interface_package, interface.name, record.name);
        try out.appendSlice(allocator, "\", {");
        for (record.fields) |field| {
            try out.appendSlice(allocator, " .");
            try append_lower(&out, allocator, field.name);
            try out.append(allocator, ' ');
            try append_type(&out, allocator, field.type_ref, record.name);
        }
        try out.appendSlice(allocator, " })\n");
    }

    for (interface.enums) |enum_decl| {
        if (std.mem.eql(u8, enum_decl.name, "error")) {
            try append_error_type_name(&out, allocator, interface.name);
        } else {
            try append_pascal(&out, allocator, enum_decl.name);
        }
        try out.appendSlice(allocator, " error = ");
        try append_cases(&out, allocator, enum_decl.cases, interface.name);
        try out.append(allocator, '\n');
    }

    for (interface.variants) |variant| {
        try append_pascal(&out, allocator, variant.name);
        try out.appendSlice(allocator, " = ");
        try append_cases(&out, allocator, variant.cases, interface.name);
        try out.append(allocator, '\n');
    }

    if (interface.aliases.len != 0 or interface.flags.len != 0) return error.UnsupportedShape;

    return out.toOwnedSlice(allocator);
}

pub fn emit_all(
    io: std.Io,
    allocator: std.mem.Allocator,
    binding: model.BindingModel,
    output_dir: []const u8,
) (EmitError || std.mem.Allocator.Error || std.Io.Dir.StatFileError || std.Io.Dir.CreateDirPathError || std.Io.Dir.WriteFileError || std.Io.Dir.RenameError || std.Io.Dir.DeleteTreeError)!void {
    const cwd = std.Io.Dir.cwd();
    const output_stat = cwd.statFile(io, output_dir, .{}) catch |err| switch (err) {
        error.FileNotFound => null,
        else => return err,
    };
    if (output_stat) |stat| {
        if (stat.kind != .directory) return error.OutputPathIsFile;
    }

    var names = std.ArrayList([]const u8).empty;
    defer {
        for (names.items) |name| allocator.free(name);
        names.deinit(allocator);
    }

    var module_hashes = std.ArrayList(emit_manifest.ModuleArtifact).empty;
    defer module_hashes.deinit(allocator);
    for (binding.interfaces) |interface| {
        const package = interface.package orelse binding.package;
        const name = try module_name(allocator, package, binding.world, interface);
        for (names.items) |existing| {
            if (std.mem.eql(u8, existing, name)) {
                allocator.free(name);
                return error.OutputNameCollision;
            }
        }
        try names.append(allocator, name);
    }

    const nonce = std.hash.Wyhash.hash(0, binding.source);
    const staging = try std.fmt.allocPrint(allocator, "{s}.tmp.{x}", .{ output_dir, nonce });
    defer allocator.free(staging);
    const backup = try std.fmt.allocPrint(allocator, "{s}.backup.{x}", .{ output_dir, nonce });
    defer allocator.free(backup);
    if (cwd.statFile(io, staging, .{}) catch null != null) return error.StagingPathExists;
    if (cwd.statFile(io, backup, .{}) catch null != null) return error.StagingPathExists;

    try cwd.createDirPath(io, staging);
    var staging_moved = false;
    defer if (!staging_moved) cwd.deleteTree(io, staging) catch {};

    for (binding.interfaces, names.items) |interface, name| {
        const source = try render_module(allocator, binding, interface);
        defer allocator.free(source);
        var source_hash: [std.crypto.hash.sha2.Sha256.digest_length]u8 = undefined;
        std.crypto.hash.sha2.Sha256.hash(source, &source_hash, .{});
        try module_hashes.append(allocator, .{ .path = name, .sha256 = source_hash });
        const path = try std.fs.path.join(allocator, &.{ staging, name });
        defer allocator.free(path);
        try cwd.writeFile(io, .{ .sub_path = path, .data = source });
    }
    const manifest_source = try emit_manifest.render_modules_with_hashes(
        allocator,
        binding,
        names.items,
        module_hashes.items,
    );
    defer allocator.free(manifest_source);
    var parsed_manifest = manifest.parse(allocator, manifest_source) catch return error.ManifestContractViolation;
    defer parsed_manifest.deinit(allocator);
    manifest.validate_binding(allocator, &parsed_manifest, binding) catch return error.ManifestContractViolation;

    const manifest_path = try std.fs.path.join(allocator, &.{ staging, "manifest.json" });
    defer allocator.free(manifest_path);
    try cwd.writeFile(io, .{ .sub_path = manifest_path, .data = manifest_source });
    manifest.validate_generated_modules(io, allocator, &parsed_manifest, manifest_path) catch
        return error.ManifestContractViolation;

    const lock = try emit_lock.render(allocator, binding);
    defer allocator.free(lock);
    const lock_path = try std.fs.path.join(allocator, &.{ staging, "wit.lock" });
    defer allocator.free(lock_path);
    try cwd.writeFile(io, .{ .sub_path = lock_path, .data = lock });

    const staging_src = try std.fs.path.join(allocator, &.{ staging, "src" });
    defer allocator.free(staging_src);
    const staging_readme = try std.fs.path.join(allocator, &.{ staging, "README.md" });
    defer allocator.free(staging_readme);
    const backup_src = try std.fs.path.join(allocator, &.{ backup, "src" });
    defer allocator.free(backup_src);
    const backup_readme = try std.fs.path.join(allocator, &.{ backup, "README.md" });
    defer allocator.free(backup_readme);

    var moved_old = false;
    var preserved_src = false;
    var preserved_readme = false;
    if (output_stat != null) {
        try cwd.rename(output_dir, cwd, backup, io);
        moved_old = true;
    }

    // Keep source inputs and project guidance beside the generated files while
    // retaining atomic replacement for the generated set itself.
    errdefer {
        if (preserved_readme) cwd.rename(staging_readme, cwd, backup_readme, io) catch {};
        if (preserved_src) cwd.rename(staging_src, cwd, backup_src, io) catch {};
        if (moved_old) cwd.rename(backup, cwd, output_dir, io) catch {};
    }
    if (moved_old) {
        if (cwd.statFile(io, backup_src, .{}) catch null) |stat| {
            if (stat.kind == .directory) {
                try cwd.rename(backup_src, cwd, staging_src, io);
                preserved_src = true;
            }
        }
        if (cwd.statFile(io, backup_readme, .{}) catch null) |stat| {
            if (stat.kind == .file) {
                try cwd.rename(backup_readme, cwd, staging_readme, io);
                preserved_readme = true;
            }
        }
    }
    cwd.rename(staging, cwd, output_dir, io) catch |err| {
        return err;
    };
    staging_moved = true;
    if (moved_old) {
        moved_old = false;
        try cwd.deleteTree(io, backup);
    }
}

fn append_cases(out: *std.ArrayList(u8), allocator: std.mem.Allocator, cases: []const model.Case, error_alias: []const u8) (EmitError || std.mem.Allocator.Error)!void {
    for (cases, 0..) |case, index| {
        if (index != 0) try out.appendSlice(allocator, " | ");
        try append_pascal(out, allocator, case.name);
        if (case.payload) |payload| {
            try out.append(allocator, '(');
            try append_type(out, allocator, payload, error_alias);
            try out.append(allocator, ')');
        }
    }
}

fn append_type(out: *std.ArrayList(u8), allocator: std.mem.Allocator, type_ref: *const model.TypeRef, error_alias: []const u8) (EmitError || std.mem.Allocator.Error)!void {
    switch (type_ref.kind) {
        .bool => try out.appendSlice(allocator, "bool"),
        .s8 => try out.appendSlice(allocator, "i8"),
        .u8 => try out.appendSlice(allocator, "u8"),
        .s16 => try out.appendSlice(allocator, "i16"),
        .u16 => try out.appendSlice(allocator, "u16"),
        .s32 => try out.appendSlice(allocator, "i32"),
        .u32 => try out.appendSlice(allocator, "u32"),
        .s64 => try out.appendSlice(allocator, "i64"),
        .u64 => try out.appendSlice(allocator, "u64"),
        .f32 => try out.appendSlice(allocator, "f32"),
        .f64 => try out.appendSlice(allocator, "f64"),
        .char => try out.appendSlice(allocator, "u32"),
        .string => try out.appendSlice(allocator, "text"),
        .unit => try out.appendSlice(allocator, "nil"),
        .named => if (std.mem.eql(u8, type_ref.name, "error"))
            try append_error_type_name(out, allocator, error_alias)
        else
            try append_pascal(out, allocator, type_ref.name),
        .list => {
            if (type_ref.args.len != 1) return error.InvalidTypeArity;
            try out.append(allocator, '[');
            try append_type(out, allocator, type_ref.args[0], error_alias);
            try out.append(allocator, ']');
        },
        .option => {
            if (type_ref.args.len != 1) return error.InvalidTypeArity;
            try append_type(out, allocator, type_ref.args[0], error_alias);
            try out.appendSlice(allocator, " | nil");
        },
        .result => {
            if (type_ref.args.len != 2) return error.InvalidTypeArity;
            try append_type(out, allocator, type_ref.args[0], error_alias);
            try out.appendSlice(allocator, " | ");
            try append_type(out, allocator, type_ref.args[1], error_alias);
        },
        .future => {
            if (type_ref.args.len != 1) return error.InvalidTypeArity;
            try out.appendSlice(allocator, "Future<");
            try append_type(out, allocator, type_ref.args[0], error_alias);
            try out.append(allocator, '>');
        },
        .stream => {
            if (type_ref.args.len != 1) return error.InvalidTypeArity;
            try out.appendSlice(allocator, "Stream<");
            try append_type(out, allocator, type_ref.args[0], error_alias);
            try out.append(allocator, '>');
        },
        .tuple => {
            if (type_ref.args.len < 2) return error.InvalidTypeArity;
            try out.appendSlice(allocator, "Tuple<");
            for (type_ref.args, 0..) |arg, index| {
                if (index != 0) try out.appendSlice(allocator, ", ");
                try append_type(out, allocator, arg, error_alias);
            }
            try out.append(allocator, '>');
        },
        .own, .borrow => {
            if (type_ref.args.len != 1) return error.InvalidTypeArity;
            try append_type(out, allocator, type_ref.args[0], error_alias);
        },
    }
}

fn append_error_type_name(out: *std.ArrayList(u8), allocator: std.mem.Allocator, interface_name: []const u8) !void {
    try append_pascal(out, allocator, interface_name);
    try out.appendSlice(allocator, "Error");
}

fn append_interface_locator(
    out: *std.ArrayList(u8),
    allocator: std.mem.Allocator,
    package: model.PackageDecl,
    interface_name: []const u8,
) !void {
    try append_raw_name(out, allocator, package.namespace);
    try out.append(allocator, ':');
    try append_raw_name(out, allocator, package.name);
    try out.append(allocator, '/');
    try append_raw_name(out, allocator, interface_name);
    try out.append(allocator, '@');
    try append_version(out, allocator, package.version);
}

fn append_wit_resource_target(
    out: *std.ArrayList(u8),
    allocator: std.mem.Allocator,
    package: model.PackageDecl,
    interface_name: []const u8,
    resource_name: []const u8,
) !void {
    try append_raw_name(out, allocator, package.namespace);
    try out.append(allocator, ':');
    try append_raw_name(out, allocator, package.name);
    try out.append(allocator, '/');
    try append_raw_name(out, allocator, interface_name);
    try out.append(allocator, '/');
    try append_raw_name(out, allocator, resource_name);
}

fn append_version(out: *std.ArrayList(u8), allocator: std.mem.Allocator, version: model.Version) !void {
    try append_fmt(out, allocator, "{d}.{d}.{d}", .{ version.major, version.minor, version.patch });
    if (version.prerelease.len != 0) {
        try out.append(allocator, '-');
        try append_raw_name(out, allocator, version.prerelease);
    }
}

fn append_raw_name(out: *std.ArrayList(u8), allocator: std.mem.Allocator, name: []const u8) !void {
    try out.appendSlice(allocator, name);
}

fn append_flat_name(out: *std.ArrayList(u8), allocator: std.mem.Allocator, name: []const u8) !void {
    for (name) |ch| {
        if (std.ascii.isAlphanumeric(ch) or ch == '_') {
            try out.append(allocator, ch);
        } else {
            try out.append(allocator, '_');
        }
    }
}

fn append_pascal(out: *std.ArrayList(u8), allocator: std.mem.Allocator, name: []const u8) !void {
    var upper = true;
    for (name) |ch| {
        if (ch == '-' or ch == '_' or ch == '.') {
            upper = true;
            continue;
        }
        if (upper) {
            try out.append(allocator, std.ascii.toUpper(ch));
            upper = false;
        } else {
            try out.append(allocator, ch);
        }
    }
}

fn append_lower(out: *std.ArrayList(u8), allocator: std.mem.Allocator, name: []const u8) !void {
    for (name) |ch| {
        if (ch == '-' or ch == '.') {
            try out.append(allocator, '_');
        } else {
            try out.append(allocator, std.ascii.toLower(ch));
        }
    }
}

fn append_fmt(out: *std.ArrayList(u8), allocator: std.mem.Allocator, comptime format: []const u8, args: anytype) !void {
    const text = try std.fmt.allocPrint(allocator, format, args);
    defer allocator.free(text);
    try out.appendSlice(allocator, text);
}
