package do:g6-2-c-min-producer@0.1.0;

interface types {
  enum error-code {
    io,
    pipe,
    invalid-mode,
  }

  resource ticket {}

  record resource-entry {
    ticket: own<ticket>,
  }
}

interface source {
  use types.{ticket};
  make-ticket: func(seed: u32) -> own<ticket>;
}

interface sink {
  use types.{error-code, resource-entry};
  consume-via-stream: async func(
    data: stream<list<resource-entry>>
  ) -> result<_, error-code>;
}

world c-min-producer {
  use types.{error-code};
  import source;
  import sink;
  export produce: async func(mode: u32) -> result<_, error-code>;
}
