package wasi:http@0.3.0-rc-2025-09-16;

interface types {
  variant error-code { dns-timeout }

  resource fields {
    constructor();
  }

  resource request {
    new: static func(
      headers: fields,
      contents: option<stream<u8>>,
      trailers: future<result<option<fields>, error-code>>,
      options: option<request-options>
    ) -> tuple<request, future<result<_, error-code>>>;
  }

  resource request-options {}
}

interface body {
  use types.{error-code};
  acquire: func() -> tuple<stream<u8>, future<result<_, error-code>>>;
}

interface probe {
  run: async func();
}

world http-request-body-probe {
  import types;
  import body;
  export probe;
}
