package wasi:filesystem@0.3.0-rc-2025-09-16;

interface types {
  use wasi:clocks/wall-clock@0.3.0-rc-2025-09-16.{datetime};

  type filesize = u64;
  type link-count = u64;

  flags path-flags {
    symlink-follow,
  }

  enum descriptor-type {
    unknown,
    block-device,
    character-device,
    directory,
    fifo,
    symbolic-link,
    regular-file,
    socket,
  }

  record descriptor-stat {
    %type: descriptor-type,
    link-count: link-count,
    size: filesize,
    data-access-timestamp: option<datetime>,
    data-modification-timestamp: option<datetime>,
    status-change-timestamp: option<datetime>,
  }

  enum error-code {
    access,
    already,
    bad-descriptor,
    busy,
    deadlock,
    quota,
    exist,
    file-too-large,
    illegal-byte-sequence,
    in-progress,
    interrupted,
    invalid,
    io,
    is-directory,
    loop,
    too-many-links,
    message-size,
    name-too-long,
    no-device,
    no-entry,
    no-lock,
    insufficient-memory,
    insufficient-space,
    not-directory,
    not-empty,
    not-recoverable,
    unsupported,
    no-tty,
    no-such-device,
    overflow,
    not-permitted,
    pipe,
    read-only,
    invalid-seek,
    text-file-busy,
    cross-device,
  }

  resource descriptor {
    stat-at: async func(
      path-flags: path-flags,
      path: string,
    ) -> result<descriptor-stat, error-code>;
  }
}

interface probe {
  use types.{descriptor, descriptor-stat, error-code, path-flags};
  run: async func(
    file: own<descriptor>,
    path-flags: path-flags,
    path: string,
  ) -> result<descriptor-stat, error-code>;
  cancel: async func();
}

world stat-at-cancel-probe {
  import types;
  export probe;
}
