package demo:marshal-record-nested-lower@1.0.0;

interface api {
  record header {
    code: u32,
    count: u64,
  }

  record writing {
    header: header,
    status: s64,
  }

  write: func(value: writing);
}
