// generated by do wit; source WIT is authoritative

send = @host_func("do:bindgen-probe/api@0.1.0", "send", (Request) -> Future<Response | ApiError>)
completion = @host_func("do:bindgen-probe/api@0.1.0", "completion", () -> Future<u32>)
events = @host_func("do:bindgen-probe/api@0.1.0", "events", () -> Stream<u8>)

Request = @wasi_resource("do:bindgen-probe/api/request", { .id i64 })
Response = @wasi_resource("do:bindgen-probe/api/response", { .id i64 })
ApiError error = Failed
